import React,{useEffect,useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import'./style.css';
const API='http://localhost:8080/api'; const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
function App(){const[products,setProducts]=useState([]),[filter,setFilter]=useState('All'),[active,setActive]=useState(null),[cart,setCart]=useState([]),[auth,setAuth]=useState(JSON.parse(localStorage.getItem('cf-user')||'null')),[showAuth,setShowAuth]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{fetch(API+'/products').then(r=>r.json()).then(setProducts)},[]);useEffect(()=>{if(auth)loadCart()},[auth]);
 const headers=()=>({'Content-Type':'application/json','Authorization':auth?.token});const loadCart=()=>fetch(API+'/cart',{headers:headers()}).then(r=>r.json()).then(setCart);const add=async p=>{if(!auth){setShowAuth(true);return}await fetch(API+'/cart',{method:'POST',headers:headers(),body:JSON.stringify({productId:p.id,quantity:1})});loadCart();setNotice(`${p.name} added to your cart.`);setTimeout(()=>setNotice(''),2500)}; const shown=filter==='All'?products:products.filter(p=>p.category===filter);const count=cart.reduce((a,i)=>a+i.quantity,0);
 return <><header><a className="brand" href="#top"><span>CF</span>Cedar <i>&</i> Form</a><nav>{['Shop','Our story','Journal'].map(x=><a href="#shop" key={x}>{x}</a>)}</nav><div className="tools"><button onClick={()=>setShowAuth(true)}>{auth?`Hi, ${auth.name.split(' ')[0]}`:'Sign in'}</button><button className="bag" onClick={()=>document.querySelector('#bag').classList.add('open')}>Bag <b>{count}</b></button></div></header>
 <main id="top"><section className="hero"><div><p className="eyebrow">Designed for staying awhile</p><h1>Furniture with a<br/><em>point of view.</em></h1><p className="lede">Thoughtful chairs for the way you gather, work, rest, and live.</p><a className="button" href="#shop">Explore the collection <span>→</span></a></div><div className="heroimage"><img src="/images/furniture-hero.png"/><p>New arrivals<br/><b>made for home</b></p></div></section>
 <section className="promise"><span>01</span><p>Crafted in enduring materials. Made for your everyday rituals.</p><span>02</span><p>Flat-rate delivery, thoughtful service, 30-day returns.</p></section>
 <section id="shop" className="collection"><div className="sectionhead"><div><p className="eyebrow">The collection</p><h2>Seat yourself.</h2></div><div className="filters">{['All','Living','Dining','Outdoor'].map(x=><button className={filter===x?'selected':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div><div className="grid">{shown.map(p=><article className="card" key={p.id}><button className="image" onClick={()=>setActive(p)}><img src={'/images/'+p.image}/><span>{p.category}</span></button><div className="productline"><div><h3>{p.name}</h3><p>{p.finish}</p></div><strong>{money(p.price)}</strong></div><button className="quick" onClick={()=>add(p)}>Add to bag <span>+</span></button></article>)}</div></section>
 <section className="newsletter"><p className="eyebrow">A little room to think</p><h2>Notes on how we live.</h2><p>New pieces, considered spaces, and stories from the workshop.</p><div><input placeholder="Your email address"/><button>Subscribe →</button></div></section></main><footer><a className="brand"><span>CF</span>Cedar <i>&</i> Form</a><p>© 2026 Cedar & Form. Furnish slowly.</p></footer>
 {active&&<ProductModal product={active} close={()=>setActive(null)} add={add}/>}<Cart cart={cart} load={loadCart} auth={auth} setNotice={setNotice}/>{showAuth&&<Auth close={()=>setShowAuth(false)} login={u=>{setAuth(u);localStorage.setItem('cf-user',JSON.stringify(u));setShowAuth(false)}}/>}{notice&&<div className="toast">{notice}</div>}</>}
function ProductModal({product:p,close,add}){return <div className="overlay" onClick={close}><div className="modal productmodal" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><img src={'/images/'+p.image}/><div><p className="eyebrow">{p.category}</p><h2>{p.name}</h2><h3>{money(p.price)}</h3><p>{p.description}</p><dl><dt>Dimensions</dt><dd>{p.dimensions}</dd><dt>Materials</dt><dd>{p.materials}</dd></dl><button className="button" onClick={()=>{add(p);close()}}>Add to bag →</button></div></div></div>}
function Auth({close,login}){const[mode,setMode]=useState('login'),[form,setForm]=useState({name:'',email:'',password:''}),[error,setError]=useState('');const submit=async e=>{e.preventDefault();let path=mode==='login'?'/auth/login':'/auth/register';let data=mode==='login'?{email:form.email,password:form.password}:form;let r=await fetch(API+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),j=await r.json();r.ok?login(j):setError(j.message||'Please try again.')};return <div className="overlay"><form className="modal auth" onSubmit={submit}><button type="button" className="close" onClick={close}>×</button><p className="eyebrow">Cedar & Form</p><h2>{mode==='login'?'Welcome back.':'Create your account.'}</h2>{mode==='register'&&<input required placeholder="Your name" onChange={e=>setForm({...form,name:e.target.value})}/>}<input required type="email" placeholder="Email address" onChange={e=>setForm({...form,email:e.target.value})}/><input required type="password" minLength="4" placeholder="Password" onChange={e=>setForm({...form,password:e.target.value})}/>{error&&<p className="error">{error}</p>}<button className="button">{mode==='login'?'Sign in':'Register'} →</button><button type="button" className="textbutton" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Need an account? Register':'Already a member? Sign in'}</button></form></div>}
function Cart({cart,load,auth,setNotice}){const total=cart.reduce((s,i)=>s+i.product.price*i.quantity,0);const remove=async id=>{await fetch(API+'/cart/'+id,{method:'DELETE',headers:{Authorization:auth.token}});load()};const checkout=async()=>{let address=prompt('Where should we deliver your order?');if(!address)return;let r=await fetch(API+'/checkout',{method:'POST',headers:{'Content-Type':'application/json',Authorization:auth.token},body:JSON.stringify({address})});if(r.ok){let o=await r.json();load();document.querySelector('#bag').classList.remove('open');setNotice(`Order ${o.confirmation} confirmed. Thank you!`)}};return <aside id="bag"><div className="baghead"><h2>Your bag</h2><button onClick={()=>document.querySelector('#bag').classList.remove('open')}>×</button></div>{cart.length?<><div className="cartitems">{cart.map(i=><div className="cartitem" key={i.id}><img src="/images/furniture-thumbnail.png"/><div><b>{i.product.name}</b><p>Qty {i.quantity}</p><strong>{money(i.product.price*i.quantity)}</strong><button onClick={()=>remove(i.id)}>Remove</button></div></div>)}</div><div className="checkout"><p><span>Subtotal</span><b>{money(total)}</b></p><small>Delivery calculated at checkout.</small><button className="button" onClick={checkout}>Secure checkout →</button></div></>:<div className="empty">Your bag is waiting for something beautiful.</div>}</aside>}
createRoot(document.getElementById('root')).render(<App/>);
